<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MyFabTry</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
   <PackageReference Update="FSharp.Core" Version="8.0.301" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Helpers.fs" />
    <Compile Include="Build.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FAKE.Core" Version="5.16.0" />
    <PackageReference Include="Fake.Core.Target" Version="6.1.3" />
    <PackageReference Include="Fake.IO.FileSystem" Version="6.1.3" />

  </ItemGroup>

</Project>
