<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="8.0.301" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="apis\UserApi.fs" />
    <Compile Include="components\Hello.fs" />
    <Compile Include="components\Router.fs" />
    <Compile Include="Index.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Browser.Dom" Version="2.20.0" />
    <PackageReference Include="Fable.Core" Version="4.5.0" />
    <PackageReference Include="Fable.Promise" Version="3.2.0" />
    <PackageReference Include="Feliz" Version="2.9.0" />
    <PackageReference Include="Feliz.Router" Version="4.0.0" />
    <PackageReference Include="Feliz.Shadcn" Version="0.9.4" />
    <PackageReference Include="Thoth.Fetch" Version="3.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.fsproj" />
  </ItemGroup>
</Project>